wandb_version: 1

ent_coef:
  desc: null
  value: 0.08940045015899835
gae_lambda:
  desc: null
  value: 0.9596841132474012
gamma:
  desc: null
  value: 0.9063217218675012
hmax:
  desc: null
  value: 42427
learning_rate:
  desc: null
  value: 4.6625301262393885e-05
loss_penalty_weight:
  desc: null
  value: 0.35769391602155376
max_grad_norm:
  desc: null
  value: 0.19125975247999535
n_steps:
  desc: null
  value: 3294
reward_scaling:
  desc: null
  value: 0.0002541306496988688
sharpe_ratio_weight:
  desc: null
  value: 0.1906886765542132
vf_coef:
  desc: null
  value: 0.1910112572649668
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1691484245.548487
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      2:
      - 1
      - 5
      - 35
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.12
      5: 0.15.7
      8:
      - 1
      - 4
      - 5
