ASSET_TICKERS = []
ASSET_TECH_INDIC_TICKERS = []

INDICATORS_STOCKSTATS = [
    "macd",
    "macds",
    "macdh",
    "trix",
    "boll",
    "boll_ub",
    "boll_lb",
    "rsi_14",
    "rsi_30",
    "cci_30",
    "dx_30",
    "close_10_mad",
    "close_30_sma",
    "close_60_sma",
    "close_200_sma",
    "rvgi",
    "rvgis"
]


ECONOMIC_INDICATOR_TICKERS = ['.AAIIB2B G Index',
                              '.DMASPX G Index',
                              '.NETBULL G Index',
                              '.NGCM% G Index',
                              '.SPE10YBR G Index',
                              '.SPPE2YBR G Index',
                              '.SPX%FWD G Index',
                              '.SPXPE G Index',
                              'AAIIBEAR Index',
                              'AAIIBOND Index',
                              'AAIIBULL Index',
                              'AAIICASH Index',
                              'AAIINEUT Index',
                              'AAIISTCK Index',
                              'AAIISVND Index',
                              'ADVN Index',
                              'ARMS Index',
                              'AUD Curncy',
                              'BCOMPR Index',
                              'BIFIFEDA Index',
                              'BIFIFEDM Index',
                              'BSPGCPUS Index',
                              'CLL Index',
                              'CONSP5MD Index',
                              'CONSSENT Index',
                              'CONSSENY Index',
                              'CPI CHNG Index',
                              'CVIX Index',
                              'DBQSGSI Index',
                              'DOEASCRD Index',
                              'DXY Curncy',
                              'ECSURPUS Index',
                              'ECSUSUUS Index',
                              'EHNFUS Index',
                              'EHUPUS Index',
                              'EURUSDV1M Curncy',
                              'EURUSDV1Y Curncy',
                              'FARBAST Index',
                              'FEDL01 Index',
                              'GDP CUR$ Index',
                              'GSCBHRSB Index',
                              'GSERCAUS Index',
                              'GSUSCAI Index',
                              'GT10 Govt',
                              'GT2 Govt',
                              'GT30 Govt',
                              'GT5 Govt',
                              'IMM0ECON Index',
                              'IMMTENCN Index',
                              'INDU Index',
                              'INJCJC Index',
                              'INJCSP Index',
                              'JPMEQGSI Index',
                              'JPMEQGSI Index',
                              'LAGITOTL Index',
                              'LEI 6MAN Index',
                              'LEI CHNG Index',
                              'LEI TOTL Index',
                              'LEI YOY Index',
                              'MOVE Index',
                              'MSXAMSIL Index',
                              'MSXAMSIS Index',
                              'NAPMNIS Index',
                              'NAPMNISH Index',
                              'NAPMNISL Index',
                              'NAPMNISS Index',
                              'NAPMNMI Index',
                              'NAPMPMI Index',
                              'NAPMPMI Index',
                              'NDX Index',
                              'NFCINBAA Index',
                              'NFCINHY Index',
                              'NFP T Index',
                              'NFP TCH Index',
                              'NFP TCH Index',
                              'NFP TMOM Index',
                              'NQBUY Index',
                              'NTMBHA Index',
                              'NTMBHV Index',
                              'NWHLAMHI Index',
                              'NWHLAMHL Index',
                              'NWHLNYHI Index',
                              'NWHLNYHL Index',
                              'NWHLNYLO Index',
                              'NWHLSEAM Index',
                              'NWHLSEND Index',
                              'NWHLSENY Index',
                              'NYAAD Index',
                              'NYSEVALU Index',
                              'NYSEVOL Index',
                              'OPCVTPCR Index',
                              'PCE DEFM Index',
                              'PCRTEQTY Index',
                              'PCRTTOTL Index',
                              'PCUSEQTR Index',
                              'PCUSINXR Index',
                              'PITLCHNG Index',
                              'PPI CHNG Index',
                              'PPI YOY Index',
                              'RVX Index',
                              'SFFRNEWS Index',
                              'SGXQIN01 Index',
                              'SKEW Index',
                              'SPGSCI Index',
                              'SUM OSC Index',
                              'TRADCAND Index',
                              'TRADCNYC Index',
                              'TRADHIGH Index',
                              'TRADHILO Index',
                              'TRADPAUS Index',
                              'TRAN Index',
                              'UMBTSENT Index',
                              'USDJPYV1M Curncy',
                              'USDJPYV3M Curncy',
                              'USEPSPVX Index',
                              'USPESPGX Index',
                              'USPESPPE Index',
                              'USURTOT Index',
                              'USYC1030 Index',
                              'USYC2Y10 Index',
                              'USYC2Y5Y Index',
                              'USYC3M2Y Index',
                              'USYC5Y30 Index',
                              'VIX Index',
                              'VIX3M Index',
                              'CESIUSD Index']
